name: Release
on:
  push:
    branches:
      - main
      - releng_release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: github
    - name: Configure Git
      run: |
        git config --global committer.email "noreply@github.com"
        git config --global committer.name "GitHub Release Workflow"
        git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global author.name "${GITHUB_ACTOR}"
    - id: install-secret-key
      name: Install gpg secret key
      run: cat <(echo -e "${{ secrets.SIGNING_KEY }}") | gpg --batch --import
    - name: Maven Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B -Dgpg.passphrase=${{ secrets.SIGNING_PASSPHRASE }} -Dgpg.keyname=${{ secrets.SIGNING_KEY_NAME }} -P sign clean release:prepare release:perform -X
