name: Test and Sign (temporary test workflow)
on:
  push:
    branches:
      - 'releng'
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - id: install-secret-key
      name: Install gpg secret key
      run: |
        cat <(echo -e "${{ secrets.SIGNING_KEY }}") | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG
    - name: Build, Test and Sign
      run: mvn -B -Dgpg.passphrase=${{ secrets.SIGNING_PASSPHRASE }} -Dgpg.keyname=${{ secrets.SIGNING_KEY_NAME }} -P sign clean package